[debug] [2023-10-28T20:28:38.686Z] ----------------------------------------------------------------------
[debug] [2023-10-28T20:28:38.689Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Fede\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2023-10-28T20:28:38.690Z] CLI Version:   12.7.0
[debug] [2023-10-28T20:28:38.690Z] Platform:      win32
[debug] [2023-10-28T20:28:38.690Z] Node Version:  v18.18.0
[debug] [2023-10-28T20:28:38.692Z] Time:          Sat Oct 28 2023 17:28:38 GMT-0300 (hora estándar de Argentina)
[debug] [2023-10-28T20:28:38.692Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-10-28T20:28:38.708Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
[debug] [2023-10-28T20:28:39.154Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2023-10-28T20:28:39.155Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=696941132&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2023-10-28T20:28:54.272Z] Error: spawn cmd ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2023-10-28T20:29:04.903Z] ----------------------------------------------------------------------
[debug] [2023-10-28T20:29:04.905Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Fede\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2023-10-28T20:29:04.906Z] CLI Version:   12.7.0
[debug] [2023-10-28T20:29:04.907Z] Platform:      win32
[debug] [2023-10-28T20:29:04.907Z] Node Version:  v18.18.0
[debug] [2023-10-28T20:29:04.908Z] Time:          Sat Oct 28 2023 17:29:04 GMT-0300 (hora estándar de Argentina)
[debug] [2023-10-28T20:29:04.908Z] ----------------------------------------------------------------------
[debug] 
[info] i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
[info] i  To change your data collection preference at any time, run `firebase logout` and log in again. 
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=132677738&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2023-10-28T20:29:10.161Z] Error: spawn cmd ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[error] 
[error] Error: An unexpected error has occurred.
